### ISSUE TITLE
Download URL Changes

### ISSUE THREAD

**Issue by sg1970** [walter-1/TSSv2#1]
Hello, 

It appears the download link changes periodically if not daily while the commit# does not change. The link I use is: https://github.com/walter-1/TSSv2/releases/download/v2022.02.11.0/TSSv2.zip.  Yesterday it was: https://github.com/walter-1/TSSv2/releases/download/v2022.02.10.0/TSSv2.zip ( The date changed but sometime after 3AM Eastern time)

The issue is it breaks my automated download process. We have a ansible driven automated process to check for updates and grab the latest and greatest TSSv2 scripts at the earliest  so we can test it before using in production. I tried using the public link [aka.ms/](http://aka.ms/getTSSv2) ... however I have issues using it in a automated process. It always aborts after download about 300KB of the zip file. So I had to use the link pasted above. 

I just wanted to know if the link can be made static? If not can I assume that it changes daily and that it will have the date embedded in the URL. Would also need to know when the change happens. 

Thanks

**Comment by walter-1** [comment]
Please do **not** downlaod from this link https://github.com/walter-1/TSSv2/releases/download/v2022.02.11.0/TSSv2.zip.
the pulic links are
- aka.ms/getTSSv2
- https://cesdiagtools.blob.core.windows.net/windows/TSSv2.zip 
and the version number is incremented with each change here: https://cesdiagtools.blob.core.windows.net/windows/TSSv2.ver
