### ISSUE TITLE
missing issue ..

### ISSUE THREAD

**Issue by sg1970** [walter-1/TSSv2#2]
Hello,

Last week I had submitted a issue here about PowerShell execution policy errors ... I cannot see that thread anymore ... any ideas ?

**Comment by sg1970** [comment]
Can the repo owner please respond and let me know if I can expect a response ?

**Comment by walter-1** [comment]
It looks like you posted the issue in another repro named **TSS**, not in **TSSv2** - see reply there.

**Comment by sg1970** [comment]
My bad. Not sure how that happened. Thanks for letting me know.

**Comment by walter-1** [comment]
Let's continue with issue https://github.com/walter-1/TSS/issues/4 and close this issue here
